stages:
  - lint
  - test

artifacts:
  paths:
    - logs/
  expire_in: 1 week

lint:
  stage: lint
  script: 
    - echo "Checking syntax..."
    - bash -n *.sh

test:
  stage: test
  script:
    - echo "Running Bash test job"
    - ./script.sh
